export const FETCH_PRODUCTS_START = 'FETCH_USERS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_USERS_ERROR';
export const SET_QUANTITY = 'SET_QUANTITY';
export const SET_INFO = 'SET_INFO';